//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowCostTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vols
    {
        public vols()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public int id_vols { get; set; }
        public System.DateTime depart_vols { get; set; }
        public System.DateTime arrivee_vols { get; set; }
        public int id_dest { get; set; }
        public int id_aero_depart { get; set; }
        public int id_aero_arriver { get; set; }
        public int prix_vols { get; set; }
        public int places_dispo_vols { get; set; }
        public int places_vols { get; set; }




        /*public String depart { get {return depart; } set { depart = depart_vols.ToString(); } }
        public String arrivee { get { return arrivee; } set { arrivee = arrivee_vols.ToString(); } }*/
    
        public virtual destinations destinations { get; set; }

        /*private string desti;
        public string Destination { get { return this.desti; } set { desti = this.destinations.ville_desti; } }*/
        public string Destination { get { return this.destinations.ville_desti; } }


        private VolsModele bd;
        public string Aero_Depart { get { ;} }
        public virtual ICollection<reservation> reservation { get; set; }
    }
}
