//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LowCostTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.vols = new HashSet<vols>();
        }
    
        public int id_clients { get; set; }
        public string nom_clients { get; set; }
        public string prenom_clients { get; set; }
        public string adresse_clients { get; set; }
        public string cp_clients { get; set; }
        public string ville_clients { get; set; }
        public string tel_clients { get; set; }
        public string mail_clients { get; set; }
        public string password_clients { get; set; }
        public string token_clients { get; set; }
    
        public virtual ICollection<vols> vols { get; set; }
    }
}
